spring.application.name=Intro-to-JPA-with-Spring-Data

# H2 Konfiguration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Wichtig: Damit die Tabellen automatisch erstellt werden
spring.jpa.hibernate.ddl-auto=update

# Optional: Damit du im Log siehst, was passiert
spring.jpa.show-sql=true


# Aktiviert die grafische Oberfläche
spring.h2.console.enabled=true
# Legt den Pfad fest, unter dem du sie aufrufst
spring.h2.console.path=/h2-console
